In [1]:
# importação array do numpy

from numpy import array

In [2]:
# lista

l = [1.0,2.0,3.0]

In [3]:
# adcionando lista a variavel a como um aray

a = array(l)

In [4]:
# visualização do array

print(a)

[1. 2. 3.]


In [5]:
# tamanho do array

print(a.shape)

(3,)


In [6]:
# tipo do array

print(a.dtype)

float64


In [7]:
# importação do metodo para criação de matriz

from numpy import empty

In [8]:
# criando uma matriz com dimensoes[3,3] e visualizando os valores

a = empty([3,3])
print(a)

[[2.42660619e-316 6.94952622e-310 6.94952627e-310]
 [6.94951634e-310 6.94951634e-310 6.94951634e-310]
 [6.94951636e-310 6.94952631e-310 3.95252517e-322]]


In [6]:
# import do metodo para criação de uma matriz de zeros
from numpy import zeros

# definindo as dimensoes da matriz
a = zeros([3,5])

In [10]:
# visualização da matriz

print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# importação do metodo para criação de uma matriz de 1

from numpy import ones

In [14]:
# definindo as dimensoes

a = ones([5])

In [15]:
# visualizando

print(a)

[1. 1. 1. 1. 1.]


In [16]:
# V stack

In [17]:
# importação array(lista horizontal) e vstack(pilha vertical)

from numpy import array
from numpy import vstack

In [18]:
# definindo o array 

a1 = array([1,2,3])
print(a1)

[1 2 3]


In [19]:
# definindo um segundo array

a2 = array([4,5,6])
print(a2)

[4 5 6]


In [20]:
# tranformação em pilha

a3 = vstack((a1,a2))

In [21]:
# visualização do resultado

print(a3)

[[1 2 3]
 [4 5 6]]


In [22]:
# visualização das dimensoes

print(a3.shape)

(2, 3)


In [23]:
#Hstack

In [24]:
# htack pilha horizontal

from numpy import hstack

In [25]:
# definindo array

a1 = array([1,2,3])
print(a1)

[1 2 3]


In [26]:
# segundo array

a2 = array([4,5,6])
print(a2)

[4 5 6]


In [27]:
# pilha horizontal

a3 = hstack((a1,a2))

In [28]:
# visualizando

print(a3)

[1 2 3 4 5 6]


In [29]:
# tamanho da pilha

print(a3.shape)

(6,)
