In [1]:
# import array

from numpy import array

In [2]:
# lista

data = [11,22,33,44,55]

In [3]:
# conversão de lista para array

data = array(data)

In [4]:
# vis

print(data)

[11 22 33 44 55]


In [5]:
# tipo da variavel

print(type(data))

<class 'numpy.ndarray'>


In [6]:
# 2-D array

In [7]:
# lista com 3 elementos

data = [[11, 22], [33,44],[55,66]]

In [8]:
# array 

data = array(data)

In [9]:
# vis

print(data)

[[11 22]
 [33 44]
 [55 66]]


In [10]:
# tipo do array

print(type(data))

<class 'numpy.ndarray'>


In [11]:
# Indexing

In [12]:
# array 

data = array([11,22,33,44,55])

In [13]:
# primeiro indice

print(data[0])

11


In [14]:
# 5 elemento

print(data[4])

55


In [15]:
# index não contem 6 elementos i[5]

print(data[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [16]:
# -1 ultimo elemento forma reversa

print(data[-1])

55


In [17]:
# primeiro elemento forma reversa

print(data[-5])

11


In [18]:
# array 

data = array([[11,22],[33,44],[55,66]])

In [21]:
# primeiro elemento do primeiro indice

data[0,0]

11

In [22]:
# todos os elementos do primeiro indice

data[0,]

array([11, 22])

In [23]:
# Slicing

In [25]:
# array

data = array([11,22,33,44,55])

In [26]:
# seleção de todos os elementos

print(data[:])

[11 22 33 44 55]


In [27]:
# seleção do primeiro até o segundo elemento(indice final é exclusivo)

data[0:1]

array([11])

In [28]:
data[-2:]

array([44, 55])

In [29]:
# 2D array

In [30]:
data = array([[11,22,33],[44,55,66],[77,88,99]])

In [31]:
X,y = data[:,:-1], data[:,-1]

In [32]:
print(X)

[[11 22]
 [44 55]
 [77 88]]


In [33]:
print(y)

[33 66 99]


In [34]:
data = array([[11,22,33],[44,55,66],[77,88,99]])

In [35]:
split = 2

In [36]:
train, test = data[:split,:], data[split:,:]

In [37]:
print(train)

[[11 22 33]
 [44 55 66]]


In [38]:
print(test)

[[77 88 99]]


In [39]:
# Reshape

In [40]:
data = array([11,22,33,44,55])

In [41]:
print(data.shape)

(5,)


In [42]:
data = [[11,22],[33,44],[55,66]]

In [43]:
data = array(data)

In [44]:
print(data.shape)

(3, 2)


In [45]:
print('Rows: %d' %data.shape[0])
print('Cols: %d' %data.shape[1])

Rows: 3
Cols: 2


In [46]:
# 1D to 2D

In [47]:
data = array([11,22,33,44,55])

In [48]:
print(data.shape)

(5,)


In [49]:
data = data.reshape((data.shape[0],1))

In [50]:
print(data.shape)

(5, 1)


In [51]:
# 2d to 3D

In [52]:
data = [[11,22], [33,44],[55,66]]

In [53]:
data = array(data)

In [54]:
print(data.shape)

(3, 2)


In [55]:
data = data.reshape((data.shape[0],data.shape[1],1))

In [56]:
print(data.shape)

(3, 2, 1)
