In [1]:
from numpy import array
from scipy.sparse import csr_matrix

In [2]:
A = array([[1,0,0,1,0,0],[0,0,2,0,0,1],[0,0,0,2,0,0]])

In [3]:
print(A)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [4]:
S = csr_matrix(A)

In [5]:
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [6]:
B = S.todense()

In [7]:
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [9]:
from numpy import count_nonzero

In [10]:
sparsity = 1.0 - count_nonzero(A)/A.size

In [11]:
print(sparsity)

0.7222222222222222


In [12]:
A.size

18